name: CI & npm publish

on:
  pull_request:
    branches: [main]
    types: [opened]

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.name 'Triston Armstrong'
      - run: git config --global user.email 'triston95strong@gmail.com'
      - run: git fetch
      - run: git checkout ${{github.head_ref}}
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push origin HEAD:${{github.head_ref}}

  build:
    needs: bump_version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run fix
      - run: npm run build
